### ISSUE TITLE
Doubts on the project

### ISSUE THREAD

**Issue by MJeremy2017** [acredjb/FBP#5]
Hi, 
I am a data scientist currently working in Singapore. I came across this project and get pretty intrigued. 

I used to work under a bookmaker and used internal data to do similar predictions and the result seemed not as promising, therefore I do have some doubts on the project, it will be appreciated if you could help to resolve my doubts:
1. the features seem to be extraordinarily simple, are you sure these features are able to achieve 80% accuracy without even considering other features?
2. your prediction task seems to be a binary classification, I wonder if your `y` label is just win or lose? If so, how do you justify the description here: `y>n*3 或 n>y*3`?
3. I had a look into your training data, and the average odds is around 1.5 while training accuracy has about 60%. I wonder based on this accuracy and odds, is it possible to get a real gain?

Thanks in advance!

**Comment by acredjb** [comment]
1.The feature is able to stand for several isues including weather and so on,because it is induced by different company's mathematics' computing.
2.Focus on 'AI-FBP'(WeChat public) or micro 'acredjb'(WeChat personal) about more infomation.



515851223

From: Jeremy Zhang
Date: 2019-12-02 23:56
To: acredjb/FBP
CC: Subscribed
Subject: [acredjb/FBP] Doubts on the project (#5)
Hi,
I am a data scientist currently working in Singapore. I came across this project and get pretty intrigued.
I used to work under a bookmaker and used internal data to do similar predictions and the result seemed not as promising, therefore I do have some doubts on the project, it will be appreciated if you could help to resolve my doubts:
the features seem to be extraordinarily simple, are you sure these features are able to achieve 80% accuracy without even considering other features? 
your prediction task seems to be a binary classification, I wonder if your y label is just win or lose? If so, how do you justify the description here: y>n*3 或 n>y*3?
